# NicheMaster_Concierge_MVP 구축 태스크

- [ ] 프로젝트 초기화 및 환경 설정 [/]
    - [ ] Next.js (App Router) 프로젝트 생성
    - [ ] Shadcn/UI 및 Tailwind CSS 설정
    - [ ] Supabase 프로젝트 연결 및 클라이언트 설정
- [ ] 데이터베이스 스키마 설계 및 생성 [ ]
    - [ ] `profiles` 테이블 (사용자 정보)
    - [ ] `tasks` 테이블 (고객 요청 및 상태 관리)
    - [ ] `messages` 테이블 (고객-관리자 소통)
- [ ] 프론트엔드 - 랜딩 페이지 및 입력 폼 구현 [ ]
    - [ ] 헤로 섹션 및 가치 제안 UI
    - [ ] 다단계 인테이크 폼 (Typeform 스타일)
- [ ] 유저 대시보드 구현 [ ]
    - [ ] 작업 상태 트래킹 (오즈의 마법사 로직)
    - [ ] 결과물 뷰어 및 채팅 인터페이스
- [ ] 관리자 대시보드 (Wizard's Workspace) 구현 [ ]
    - [ ] 칸반 스타일 태스크 큐
    - [ ] AI Assist Workspace (LLM 연동 및 결과 편집)
    - [ ] 고객 관리 (CRM) 도구
- [ ] 백엔드 로직 및 API 구현 [ ]
    - [ ] 결과 제출 API (`submit-result`)
    - [ ] 결제 모듈 연동 (Stripe 모의 구현)
- [ ] 검증 및 마무리 [ ]
    - [ ] 전체 사용자 흐름 테스트
    - [ ] 결과물 및 스크린샷 캡처
